start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\nossl_433_persistent
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\nossl_433_temporary
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\nossl_500_persistent
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\nossl_500_temporary
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\nossl_501_persistent
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\nossl_501_temporary
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_09_persistent_d+v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_09_temporary_d+v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_10_persistent_d+v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_433_10_temporary_d+v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_09_persistent_d+v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_09_temporary_d+v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_10_persistent_d+v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_500_10_temporary_d+v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_09_persistent_d+v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_09_temporary_d+v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_10_persistent_d+v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbuffer_501_10_temporary_d+v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_433_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_500_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslglobal_501_08_temporary_d-v+s+k+

shutdown -s -f -t 0