start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_433_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_500_08_temporary_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_01_persistent_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_01_temporary_d-v-s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_02_persistent_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_02_temporary_d-v-s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_03_persistent_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_03_temporary_d-v+s-k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_04_persistent_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_04_temporary_d-v-s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_05_persistent_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_05_temporary_d-v-s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_06_persistent_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_06_temporary_d-v+s+k-
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_07_persistent_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_07_temporary_d-v+s-k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_08_persistent_d-v+s+k+
start /WAIT run_config.bat c:\PlatformIO\dzen\https_requests\profiles\sslbundle_501_08_temporary_d-v+s+k+

shutdown -s -f -t 0